name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/deployment.yaml'  # ignore changes to deployment.yaml to avoid loops

permissions:
  packages: write   # allow pushing to GHCR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      # 2. Set lowercase image name in env
      - name: Set lowercase image name
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ews500
          password: ${{ secrets.GH_PAT }}

      # 5. Build and push image with commit SHA + latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest

      # 6. Update deployment.yaml with new SHA tag
      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|image: ${{ env.IMAGE_NAME }}:.*|image: ${{ env.IMAGE_NAME }}:${{ github.sha }}|" k8s/deployment.yaml

      # 7. Commit and push manifest change
      - name: Commit and push updated manifest
        run: |
          git config user.name "ews500"
          git config user.email "ewandavies05@gmail.com"
          git pull origin ${{ github.ref_name }} --rebase
          git add k8s/deployment.yaml
          git commit -m "Update image to ${{ github.sha }}"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
