name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  packages: write   # allow pushing to GHCR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set lowercase image name with commit SHA
      - name: Set image name
        run: echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}:${GITHUB_SHA}" >> $GITHUB_ENV

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ews500
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5. Build and push image with two tags: commit SHA + latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}
            ghcr.io/${{ github.repository,, }}:latest